# Site settings
title: Afshin Moatari
description: 'looking  for infinity...'
url: 'afshinmoatari.me'
baseurl: '/'
google_analytics: 'UA-30334661-2'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Afshin Moatari'
  email: afshin.moatari@gmail.com
  twitter_username: Afshin_Moatari
  facebook_username: afshin.moatari
  github_username: AfshinMoatari
  linkedin_username: Afshin Moatari
  behance_username: afshinmoated6e
  codepen_username : Afshin-Moatari

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins : ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'vendor']
